function S = ancf_shape(x, L, derivative)
%ANCF_SHAPE Cubic Hermite ANCF shape functions and derivatives.
xi = x / L;
switch derivative
    case 0
        S = [1 - 3*xi^2 + 2*xi^3; ...
             L*(xi - 2*xi^2 + xi^3); ...
             3*xi^2 - 2*xi^3; ...
             L*(-xi^2 + xi^3)];
    case 1
        S = [(6*xi^2 - 6*xi)/L; ...
             1 - 4*xi + 3*xi^2; ...
             (-6*xi^2 + 6*xi)/L; ...
             -2*xi + 3*xi^2];
    case 2
        S = [(12*xi - 6)/L^2; ...
             (-4 + 6*xi)/L; ...
             (6 - 12*xi)/L^2; ...
             (-2 + 6*xi)/L];
    otherwise
        error('ancf_shape:Derivative', 'Derivative must be 0, 1, or 2.');
end
end
